### ISSUE TITLE
deepl.usePro will not be set in initial setup

### ISSUE THREAD

**Issue by pstiegele** [soerenuhrbach/vscode-deepl#26] opened 2023-03-07 17:16 UTC
Hi,
thanks for the plugin, it's great!

I installed the plugin and tried the translation. I got a request to insert my API key and a question if I use the deepl pro plan (I'm not, so I selected `No`).
The translation wasn't working: It showed a notification "Translating..." but nothing happened. 

I found out, that the parameter `deepl.usePro` wasn't added to my settings. After adding it manually (`"deepl.usePro": false`) the translation worked fine. 

I would assume that after asking the plugin would save the answer - I can reproduce this problem on my second desktop.

**Comment by soerenuhrbach** [comment] 2023-06-12 17:15
Hi,

I could not reproduce the behaviour. The plugin saves the property `deepl.usePro`.
So I will close this issue.

Thx for using the extension. :)

**Closed by soerenuhrbach** 2023-06-12 17:15 UTC
